import { notFound } from 'next/navigation';
import Link from 'next/link';
import type { Route } from 'next';
import { getPostBySlug, getPostSlugs } from '@/lib/markdown';
import { MarkdownRenderer } from '@/components/markdown-renderer';
import { TableOfContents } from '@/components/blog/TableOfContents';
import { Comments } from '@/components/blog/Comments';
import { BlogPostHero } from '@/components/blog/BlogPostHero';
import { Calendar, ArrowLeft, Tag, User } from 'lucide-react';
import { locales } from '../../../../i18n';
import { canonical as canonicalUrl } from '@/lib/seo/canonical';
import { hreflangAlternates } from '@/lib/seo/hreflang';

type Props = {
  params: { locale: string; slug: string };
};

export function generateStaticParams() {
  const slugs = getPostSlugs();
  return locales.flatMap((locale) =>
    slugs.map((file) => ({
      locale,
      slug: file.replace(/\.md$/, ''),
    }))
  );
}

export async function generateMetadata({ params: { locale, slug } }: Props) {
  const post = getPostBySlug(slug);
  if (!post) return {};

  const path = `/blog/${slug}`;
  const url = canonicalUrl(locale, path);

  // OG / Twitter cards need ABSOLUTE image URLs. Twitter's crawler in
  // particular has been unreliable about resolving relative paths
  // against the page URL; iMessage / Slack / Discord are forgiving but
  // Twitter rejects or silently strips the card when the image URL
  // doesn't have an origin. Always emit https://agentos.sh/... here.
  //
  // Image-resolution priority:
  //   1. The 1200x630 OG card generated by `gen:og` from the
  //      title-banner / stat-banner SVG templates. Canonical Twitter
  //      summary_large_image dimensions, branded layout, no surprises.
  //   2. The frontmatter `image` field (an in-content screenshot the
  //      author chose) — used when the OG generator hasn't run for
  //      this slug yet.
  //   3. The site default at /og-image-v2.png.
  const SITE_ORIGIN = 'https://agentos.sh';
  const generatedOgPath = `/img/blog/og/${slug}.png`;
  const ogPath = post.image && post.image.startsWith('/img/blog/og/')
    ? post.image
    : generatedOgPath;
  const ogImageUrl = `${SITE_ORIGIN}${ogPath}`;
  // Fallback to the author-supplied content image if it's the only
  // thing we have. (post.image is always relative.)
  const fallbackImageUrl = post.image
    ? `${SITE_ORIGIN}${post.image}`
    : `${SITE_ORIGIN}/og-image-v2.png`;

  return {
    title: `${post.title} — AgentOS Blog`,
    description: post.excerpt || post.title,
    keywords: post.keywords || '',
    alternates: {
      canonical: url,
      languages: hreflangAlternates(path),
    },
    openGraph: {
      title: post.title,
      description: post.excerpt || post.title,
      url,
      siteName: 'AgentOS',
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: post.title,
          type: 'image/png',
        },
        // Secondary: the in-content hero image, when present, so
        // crawlers that pick the largest available image (some
        // implementations) still get a high-quality option.
        ...(post.image && !post.image.startsWith('/img/blog/og/')
          ? [{ url: fallbackImageUrl, alt: post.title }]
          : []),
      ],
      type: 'article',
      publishedTime: post.date,
      authors: [post.author || 'Frame'],
    },
    twitter: {
      card: 'summary_large_image' as const,
      title: post.title,
      description: post.excerpt || post.title,
      // Explicit twitter:image. Twitter will not always fall back to
      // og:image, especially when card='summary_large_image'. Absolute
      // URL, 2:1 ratio, image/png.
      images: [ogImageUrl],
      creator: '@manicagencyhq',
    },
  };
}

export default function BlogPostPage({ params: { locale, slug } }: Props) {
  const post = getPostBySlug(slug);
  if (!post) notFound();

  const blogHref = `/${locale}/blog`;
  const canonical = canonicalUrl(locale, `/blog/${slug}`);

  return (
    <main id="main-content" className="relative overflow-x-clip bg-[var(--color-background-primary)] text-[var(--color-text-primary)]">
      {/* Article JSON-LD.
          Author Org vs Person: "AgentOS Team" and similar collective
          names map to Organization Frame; everything else (e.g. "Johnny
          Dunn") is treated as a Person. dateModified uses post.updated
          when present, falls back to post.date. articleSection comes
          from the post category. inLanguage carries the locale so
          Google ranks correctly per-region. Image becomes an
          ImageObject because Google's Rich Results test prefers it. */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Article',
            headline: post.title,
            description: post.excerpt || post.title,
            datePublished: post.date,
            dateModified: post.updated || post.lastModified || post.date,
            inLanguage: locale,
            ...(post.category ? { articleSection: post.category } : {}),
            author:
              !post.author || /\b(team|inc|llc|ai|labs|group)\b/i.test(post.author)
                ? {
                    '@type': 'Organization',
                    name: 'Frame',
                    url: 'https://frame.dev',
                  }
                : {
                    '@type': 'Person',
                    name: post.author,
                    url: 'https://frame.dev',
                  },
            publisher: {
              '@type': 'Organization',
              name: 'Frame',
              url: 'https://frame.dev',
              logo: {
                '@type': 'ImageObject',
                url: 'https://agentos.sh/og-image-v2.png',
                width: 1200,
                height: 630,
              },
            },
            mainEntityOfPage: canonical,
            image: {
              '@type': 'ImageObject',
              url: post.image
                ? `https://agentos.sh${post.image}`
                : 'https://agentos.sh/og-image-v2.png',
              width: 1200,
              height: 630,
            },
          }),
        }}
      />
      {/* BreadcrumbList JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'BreadcrumbList',
            itemListElement: [
              { '@type': 'ListItem', position: 1, name: 'Home', item: canonicalUrl(locale, '/') },
              { '@type': 'ListItem', position: 2, name: 'Blog', item: canonicalUrl(locale, '/blog') },
              { '@type': 'ListItem', position: 3, name: post.title, item: canonical },
            ],
          }),
        }}
      />

      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute inset-0 bg-gradient-to-br from-purple-500/10 via-transparent to-blue-500/10" />
      </div>

      <div className="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-24">
        {/* Back link */}
        <Link
          href={blogHref as Route}
          className="inline-flex items-center gap-1.5 text-sm font-medium text-[var(--color-text-muted)] hover:text-[var(--color-text-link)] transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" aria-hidden="true" />
          Back to blog
        </Link>

        <div className="lg:grid lg:grid-cols-[minmax(0,3fr)_minmax(0,1fr)] lg:gap-x-12">
          <div className="min-w-0 max-w-3xl">
            {/* Post header */}
            <header className="mb-10">
              {/* Eyebrow row: thin gradient accent + meta items separated by tiny dot bullets */}
              <div className="flex items-center gap-3 mb-5 text-xs">
                <span
                  aria-hidden
                  className="block h-[2px] w-8 rounded-full"
                  style={{
                    background:
                      'linear-gradient(90deg, hsl(180, 95%, 60%), hsl(270, 85%, 65%))',
                  }}
                />
                {post.category && (
                  <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-[0.18em] bg-[var(--color-text-link)]/10 text-[var(--color-text-link)] border border-[var(--color-text-link)]/30">
                    <Tag className="w-3 h-3" aria-hidden="true" />
                    {post.category}
                  </span>
                )}
                <span className="text-[var(--color-text-muted)]/40">·</span>
                <span className="flex items-center gap-1.5 text-[var(--color-text-muted)] tabular-nums">
                  <Calendar className="w-3 h-3" aria-hidden="true" />
                  {new Date(post.date).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
                </span>
                {post.author && (
                  <>
                    <span className="text-[var(--color-text-muted)]/40">·</span>
                    <span className="flex items-center gap-1.5 text-[var(--color-text-muted)]">
                      <User className="w-3 h-3" aria-hidden="true" />
                      {post.author}
                    </span>
                  </>
                )}
              </div>

              {/* Title — refined typography, tighter line height and letter-spacing for premium feel */}
              <h1 className="text-[2rem] sm:text-4xl lg:text-[2.75rem] font-bold tracking-tight text-[var(--color-text-primary)] leading-[1.1]">
                {post.title}
              </h1>

              {/* Dek / lead paragraph: left-border accent, slightly muted, smaller than the body */}
              {post.excerpt && (
                <div
                  className="mt-6 pl-5 border-l-2 text-[15px] sm:text-base text-[var(--color-text-secondary)] leading-relaxed max-w-2xl"
                  style={{
                    borderImage:
                      'linear-gradient(180deg, hsl(180, 95%, 60%) 0%, hsl(270, 85%, 65%) 100%) 1',
                  }}
                >
                  {post.excerpt}
                </div>
              )}
            </header>

            {/* In-page hero: always the branded BlogPostHero component
                (AgentOS logo + dark canvas + cyan/violet radial accents).
                Posts with heroStat + heroLabel render a stat layout;
                everything else renders the post title in gradient text on
                the same canvas. Consistent brand identity across every
                article body. The frontmatter `image` field still ships
                with the post for OG/social-card sharing. */}
            <BlogPostHero post={post} />

            {/* Inline TOC for mobile (lg:hidden); the sticky right-rail
                takes over at lg+ breakpoints and is rendered below the
                article column inside the same grid */}
            <TableOfContents content={post.content} articleTitle={post.title} placement="inline" />

            {/* Post content */}
            <MarkdownRenderer content={post.content} />

            {/* Comments (giscus when configured, friendly stub otherwise) */}
            <Comments slug={slug} />


            {/* Footer */}
            <footer className="mt-16 pt-8 border-t border-[var(--color-border-subtle)]">
              <Link
                href={blogHref as Route}
                className="inline-flex items-center gap-1.5 text-sm font-medium text-[var(--color-text-link)] hover:underline"
              >
                <ArrowLeft className="w-4 h-4" aria-hidden="true" />
                Back to all articles
              </Link>
            </footer>
          </div>

          {/* Sticky right-rail table of contents (lg+ only) */}
          <TableOfContents content={post.content} articleTitle={post.title} />
        </div>
      </div>
    </main>
  );
}
