"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Search, ExternalLink, FileText } from "lucide-react";

interface DocSearchProps {
  triggerClassName?: string;
  triggerLabel?: string;
}

interface SearchDoc {
  title: string;
  url: string;
  content?: string;
}

const DOCS_BASE = "https://docs.agentos.sh";

/**
 * Search modal that fetches a lightweight search manifest from docs.agentos.sh,
 * then filters results inline as you type.  Falls back to a curated quick-link
 * list when the manifest cannot be loaded.
 *
 * The manifest (`search-docs.json`, ~60 KB) is generated by the
 * `search-manifest` Docusaurus plugin at build time and contains the first
 * ~500 chars of each page, which enables full-text search without pulling the
 * 16 MB lunr index that `@easyops-cn/docusaurus-search-local` emits.
 */
export function DocSearch({ triggerClassName, triggerLabel }: DocSearchProps) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [docs, setDocs] = useState<SearchDoc[]>([]);
  const [loading, setLoading] = useState(false);
  const fetchedRef = useRef(false);

  // ── Keyboard shortcut ──────────────────────────────────────────────
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.defaultPrevented) return;
      if (e.key === "Escape" && open) {
        e.preventDefault();
        setOpen(false);
        setQuery("");
        return;
      }
      if (open) return;
      const tag = document.activeElement?.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA") return;
      if (e.key === "/" || ((e.metaKey || e.ctrlKey) && e.key === "k")) {
        e.preventDefault();
        setOpen(true);
      }
    };
    window.addEventListener("keydown", onKeyDown, { capture: true });
    return () => window.removeEventListener("keydown", onKeyDown, { capture: true });
  }, [open]);

  // Lock background scroll while modal is open
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  // ── Fetch lightweight manifest on first open ───────────────────────
  useEffect(() => {
    if (!open || fetchedRef.current) return;
    setLoading(true);
    const controller = new AbortController();
    let cancelled = false;

    fetch(`${DOCS_BASE}/search-docs.json`, { signal: controller.signal })
      .then(async (res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data: Array<{ t: string; u: string; c?: string }> = await res.json();
        if (cancelled) return;
        fetchedRef.current = true;
        setDocs(
          data
            .filter((d) => d.t && d.u)
            .map((d) => ({ title: d.t, url: d.u, content: d.c ?? "" })),
        );
      })
      .catch((error) => {
        if ((error as Error).name === "AbortError") return;
        // Manifest not deployed yet — silently fall back to curated list
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [open]);

  // ── Curated fallback when the manifest hasn't been deployed yet ────
  const fallbackDocs: SearchDoc[] = useMemo(
    () => [
      { title: "Getting Started", url: "/getting-started/high-level-api", content: "generateText streamText generateImage generateAudio agent provider multimodal image text audio vision model llm installation quickstart" },
      { title: "Multi-Agent Agency API", url: "/features/agency-api", content: "agency dependsOn graph sequential parallel hierarchical multi-agent orchestration coordination strategy" },
      { title: "Emergent Capabilities", url: "/features/emergent-capabilities", content: "forge tool sandbox compose LLM judge tiered emergent dynamic capability creation runtime" },
      { title: "Voice Pipeline", url: "/features/voice-pipeline", content: "voice stt tts vad barge-in endpoint detection telephony speech recognition synthesis realtime streaming" },
      { title: "Capability Discovery", url: "/features/capability-discovery", content: "discovery semantic tier token reduction embedding search capabilities tools skills" },
      { title: "System Architecture", url: "/architecture/system-architecture", content: "diagram gmi orchestrator runtime components architecture overview design system" },
      { title: "Cognitive Memory", url: "/features/cognitive-memory", content: "memory cognitive ebbinghaus decay working memory baddeley consolidation recall storage retrieval long-term short-term episodic semantic knowledge graph" },
      { title: "Multimodal RAG", url: "/features/multimodal-rag", content: "multimodal RAG retrieval augmented generation image audio video embedding vector similarity search knowledge base context ingestion" },
      { title: "Guardrails", url: "/features/guardrails", content: "pii redaction content filter guardrail pipeline safety moderation security privacy" },
      { title: "Provenance & Immutability", url: "/features/provenance-immutability", content: "provenance audit ledger tombstone signed event immutability traceability history" },
      { title: "workflow() DSL", url: "/features/workflow-dsl", content: "workflow steps DAG pipeline yaml checkpointing orchestration automation" },
      { title: "Deep Research", url: "/features/deep-research", content: "deep research query classification multi-source investigation analysis" },
      { title: "Speech Providers", url: "/features/speech-providers", content: "deepgram whisper elevenlabs speech provider catalog stt tts voice recognition synthesis" },
      { title: "Telephony Providers", url: "/features/telephony-providers", content: "twilio telnyx plivo telephony call webhook phone inbound outbound" },
      { title: "Extensions Overview", url: "/extensions", content: "extension catalog registry channel adapter plugin integration ecosystem" },
      { title: "Evaluation Framework", url: "/features/evaluation-framework", content: "eval benchmark grader candidate experiment evaluation testing quality metrics" },
      { title: "LLM Providers", url: "/features/llm-providers", content: "openai anthropic google groq together ollama deepseek provider model llm" },
      { title: "Tool Calling", url: "/architecture/tool-calling-and-loading", content: "tool calling function tools loading registration use call invoke schema" },
      { title: "Skills", url: "/skills/skills-extension", content: "skill skills extension registry curated prompt instruction behavior" },
      { title: "API Reference", url: "/api/", content: "typedoc api reference class interface types sdk typescript" },
    ],
    [],
  );

  const searchableIndex = docs.length > 0 ? docs : fallbackDocs;

  // ── Scoring ────────────────────────────────────────────────────────
  const results = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (q.length < 2) return [];

    const words = q.split(/\s+/).filter((w) => w.length >= 2);

    return searchableIndex
      .map((doc) => {
        const t = doc.title.toLowerCase();
        const c = (doc.content || "").toLowerCase();
        let score = 0;

        // Exact / prefix / substring match on title
        if (t === q) score += 200;
        else if (t.startsWith(q)) score += 100;
        else if (t.includes(q)) score += 60;

        // Full-phrase match on content
        if (c.includes(q)) score += 40;

        // Per-word matching
        for (const word of words) {
          if (t.includes(word)) score += 15;
          if (c.includes(word)) score += 8;
        }
        return { doc, score };
      })
      .filter((r) => r.score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, 12)
      .map((r) => r.doc);
  }, [query, searchableIndex]);

  // Reset selection when results change
  useEffect(() => {
    setSelectedIndex(0);
  }, [results]);

  // ── Navigation ─────────────────────────────────────────────────────
  const navigate = useCallback((doc: SearchDoc) => {
    const url = doc.url.startsWith("http") ? doc.url : `${DOCS_BASE}${doc.url}`;
    window.open(url, "_blank", "noopener,noreferrer");
    setOpen(false);
    setQuery("");
  }, []);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((i) => Math.min(i + 1, results.length - 1));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex((i) => Math.max(i - 1, 0));
      } else if (e.key === "Enter") {
        e.preventDefault();
        if (results[selectedIndex]) navigate(results[selectedIndex]);
      }
      // Escape is handled by the global listener so it works even when
      // the input has lost focus.
    },
    [results, selectedIndex, navigate],
  );

  const close = useCallback(() => {
    setOpen(false);
    setQuery("");
  }, []);

  // ── Hint text ──────────────────────────────────────────────────────
  const hint = loading
    ? "Loading..."
    : results.length > 0
      ? `${results.length} result${results.length !== 1 ? "s" : ""}`
      : "";

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <>
      <button
        type="button"
        className={
          triggerClassName ??
          "inline-flex items-center gap-2 rounded-full border border-slate-200/70 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-brand hover:text-brand dark:border-slate-700 dark:text-slate-200 dark:hover:border-brand"
        }
        onClick={() => setOpen(true)}
        aria-label="Search documentation"
        title="Search (/ or Ctrl+K)"
      >
        <Search className="w-4 h-4" />
        {triggerLabel ?? null}
      </button>

      {open && (
        <div
          className="doc-search-backdrop fixed inset-0 z-[60] flex items-start justify-center px-4 pt-[14vh] sm:pt-[16vh]"
          onMouseDown={(e) => {
            // Close when the press starts on the backdrop, not on the panel
            if (e.target === e.currentTarget) close();
          }}
          role="dialog"
          aria-modal="true"
          aria-label="Search documentation"
        >
          <div
            className="doc-search-panel w-full max-w-xl overflow-hidden"
            onMouseDown={(e) => e.stopPropagation()}
          >
            {/* ── Input ──────────────────────────────────────────── */}
            <div className="doc-search-input-row">
              <Search className="w-4 h-4 shrink-0 doc-search-icon" />
              <input
                autoFocus
                type="text"
                placeholder="Search documentation…"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={handleKeyDown}
                className="doc-search-input"
                aria-label="Search documentation"
              />
              <button
                type="button"
                onClick={close}
                className="doc-search-esc"
                aria-label="Close search"
                title="Close (Esc)"
              >
                ESC
              </button>
            </div>

            {/* ── Results ────────────────────────────────────────── */}
            <div className="doc-search-results">
              {results.length > 0 ? (
                <div className="doc-search-results-inner">
                  <p className="doc-search-hint">{hint}</p>
                  {results.map((doc, i) => (
                    <button
                      key={doc.url}
                      onClick={() => navigate(doc)}
                      onMouseEnter={() => setSelectedIndex(i)}
                      className={`doc-search-result${i === selectedIndex ? " is-active" : ""}`}
                    >
                      <FileText className="w-3.5 h-3.5 shrink-0 doc-search-result-icon" />
                      <div className="flex-1 min-w-0">
                        <div className="truncate">{doc.title}</div>
                      </div>
                      <ExternalLink className="w-3 h-3 shrink-0 doc-search-result-ext" />
                    </button>
                  ))}
                </div>
              ) : query.trim().length >= 2 ? (
                <div className="doc-search-empty">
                  No results for &ldquo;{query.trim()}&rdquo;
                </div>
              ) : (
                <div className="doc-search-empty doc-search-empty-tip">
                  Type to search across guides, features, and API reference.
                </div>
              )}
            </div>

            {/* ── Footer ─────────────────────────────────────────── */}
            <div className="doc-search-footer">
              <span>
                <kbd>↑↓</kbd> navigate
              </span>
              <span>
                <kbd>↵</kbd> open
              </span>
              <span>
                <kbd>esc</kbd> close
              </span>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

export default DocSearch;
